[Account]
BrokerID=
UserID=
InvestorID=
Password=
AuthCode=
AppID=
ProductInfo=1.0.0
CurrencyID=CNY

[Network]
# 交易前置
TradeFront=tcp://112.65.19.116:32205
# 行情前置 (注意端口不同)
MdFront=tcp://112.65.19.116:32213